Apartment/Apartment/Controllers/ApartmentResidentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using Apartment.Models;

namespace Apartment.Controllers
{
    public class ApartmentResidentsController : Controller
    {
        private Apartment_Expenses2Entities db = new Apartment_Expenses2Entities();

        // GET: ApartmentResidents
        public Boolean IsAuthorize()
        {
            if (!User.Identity.Name.IsEmpty())
            {
                return true;
            }
            return false;
        }
        public ActionResult Index()
        {

            if (IsAuthorize())
            {
                return View(db.ApartmentResidents.ToList());
            }
            return RedirectToAction("LogIn", "LogIn");
        }

        // GET: ApartmentResidents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApartmentResident apartmentResident = db.ApartmentResidents.Find(id);
            if (apartmentResident == null)
            {
                return HttpNotFound();
            }
            if (IsAuthorize())
            {
                return View(apartmentResident);
            }
            return RedirectToAction("LogIn", "LogIn");
        
    }

        // GET: ApartmentResidents/Create
        public ActionResult Create()
        {
            if (IsAuthorize())
            {
                return View();
            }
            return RedirectToAction("LogIn", "LogIn");
        
    }

        // POST: ApartmentResidents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Resident_id,FirstName,LastName,FlatNumber,OwnerShipType,ContactNo,Email,MoveInDate")] ApartmentResident apartmentResident)
        {
            if (ModelState.IsValid)
            {
                db.ApartmentResidents.Add(apartmentResident);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(apartmentResident);
        }
        [ChildActionOnly]

        // GET: ApartmentResidents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApartmentResident apartmentResident = db.ApartmentResidents.Find(id);
            if (apartmentResident == null)
            {
                return HttpNotFound();
            }
            return View(apartmentResident);
        }

        // POST: ApartmentResidents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Resident_id,FirstName,LastName,FlatNumber,OwnerShipType,ContactNo,Email,MoveInDate")] ApartmentResident apartmentResident)
        {
            if (ModelState.IsValid)
            {
                db.Entry(apartmentResident).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(apartmentResident);
        }

        // GET: ApartmentResidents/Delete/5
        [ChildActionOnly]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApartmentResident apartmentResident = db.ApartmentResidents.Find(id);
            if (apartmentResident == null)
            {
                return HttpNotFound();
            }
            return View(apartmentResident);
        }

        // POST: ApartmentResidents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ApartmentResident apartmentResident = db.ApartmentResidents.Find(id);
            db.ApartmentResidents.Remove(apartmentResident);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Apartment/Apartment/Controllers/MonthlyController.cs
using Apartment.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Apartment.Controllers
{
    public class MonthlyController : Controller
    {
        HttpClient httpClient;
        public MonthlyController()
        {
            httpClient=new HttpClient();
            Uri u = new Uri("http://localhost:54026/api/");
            httpClient.BaseAddress = u;
        }

        public ActionResult Index()
        {

            List<MonthlyMaintainance> li = new List<MonthlyMaintainance>();
            HttpResponseMessage reposnse = httpClient.GetAsync(httpClient.BaseAddress + "/Monthly").Result;
            if (reposnse.IsSuccessStatusCode)
            {
                string Data = reposnse.Content.ReadAsStringAsync().Result;
                li = JsonConvert.DeserializeObject<List<MonthlyMaintainance>>(Data);
            }
            return View(li);

        }
    }
}

Apartment/Apartment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Apartment Expenses", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse  pull-right">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.Identity.Name.IsEmpty())
                    {
                        <li>@Html.ActionLink("LogIn", "LogIn", "LogIn", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                    }
                    else
                    { 
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("LogOut", "LogOut", "LogIn", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Monthly Dues", "Index", "Monthly", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Details", "Index", "ApartmentResidents", new { area = "" }, new { @class = "nav-link" })</li>
                        
                    }

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Apartment Expenses</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>